#!/usr/bin/env ruby
# coding: utf-8
# Copyright muflax <mail@muflax.com>, 2012
# License: GNU GPL 3 <http://www.gnu.org/copyleft/gpl.html>

# Set .beeminderrc as per `beemind`, then run `beemind-fitocracy -u USER -p PASS`.

require "beeminder"
require "mechanize"
require "trollop"
require "yaml"

opts = Trollop::options do
  opt :username, "username", :type => String
  opt :password, "password", :type => String
  opt :goal, "goal", :type => String, :default => "fitocracy"
end

# crawl site
agent = Mechanize.new
agent.follow_meta_refresh = true
agent.user_agent_alias    = 'Windows Mozilla'

# login
login_url  = "https://www.fitocracy.com/accounts/login/?next=%2Flogin%2F"
login_page = agent.get login_url
login_form = login_page.form_with(:id => 'username-login-form')

csrfmiddlewaretoken = login_form['csrfmiddlewaretoken']

logged_in = agent.post('https://www.fitocracy.com/accounts/login/', {
                         "csrfmiddlewaretoken" => csrfmiddlewaretoken,
                         "is_username"         => "1",
                         "json"                => "1",
                         "next"                => "/home/",
                         "username"            => opts[:username],
                         "password"            => opts[:password]
                       })

if !(logged_in.body.include? "error")
  # get points
  profile_url = "https://www.fitocracy.com/profile/#{opts[:username]}"
  profile_page = agent.get profile_url

  li = profile_page.search("li#stat-points").first

  score = Integer(li.content.split.first.gsub(",", ""))
  
  # send to beeminder
  config     = YAML.load File.open("#{Dir.home}/.beeminderrc")
  bee        = Beeminder::User.new config["token"]
  fit_goal   = bee.goal opts[:goal]
  last_score = fit_goal.datapoints.max_by{|x| x.value}.value.to_i

  if score > last_score
    bee.send opts[:goal], score, "automatic update (+#{score - last_score})"
  end
end


