#!/usr/bin/env python3
# Copyright muflax <mail@muflax.com>, 2010
# License: GNU GPL 3 <http://www.gnu.org/copyleft/gpl.html>

import optparse, os, subprocess, sys, platform

def main():
    p = optparse.OptionParser()
    p.add_option("-+", "--vol", action="store", dest="volume", type="int", 
                 help="increase volume by VOLUME")
    p.add_option("-l", "--left", action="store_const", const="left", dest="where", 
                 help="left screen", default="right")
    p.add_option("-r", "--right", action="store_const", const="right", dest="where", 
                 help="right screen")
    p.add_option("-s", "--speed", action="store", dest="speed", type="float", 
                 help="increase speed by SPEED")
    p.add_option("-y", "--youtube", action="store_const", const="youtube",
                 dest="youtube", help="youtube mode")

    opt, args = p.parse_args()

    host = platform.node()
    display = ":0.0"
    # host-specific options
    if host == "azathoth":
        if opt.where == "left":
            args[:0] = ["-delay", "-0.05"]
    
        # screen handling
        if opt.where == "left":
            args[:0] = ["-xineramascreen", "0"]
        elif opt.where == "right":
            args[:0] = ["-xineramascreen", "1"]
        else:
            optparse.error("wtf is '{}'?!".format(opt.where))

    # audio filter
    args[:0] = ["-af-add", "scaletempo"]
    if opt.volume:
        args[:0] = ["-af-add", "volume={}".format(opt.volume)]
    
    # speed increase
    if opt.speed:
        args[:0] = ["-speed", "{}".format(opt.speed)]

    # youtube mode: if we're in a youtube-y folder, add a speed-up
    if opt.youtube == "youtube":
        path = os.getcwd()
        for s in ["/home/amon/youtube", "/home/amon/テレビ/lessons"]:
            if s in path:
                args[:0] = ["-speed", "1.4"]
    
    # azathoth needs a wrapper, though
    cmd = ["mplayer"]
    os.environ["DISPLAY"] =  display
    if host == "azathoth" and opt.where == "right":
        try:
            os.system("nvidia-settings -a XVideoSyncToDisplay=DFP-1 >/dev/null")
            ret = subprocess.call(cmd + args, env=os.environ)
        except Exception as e:
            print(e)
        finally:
            os.system("nvidia-settings -a XVideoSyncToDisplay=DFP-0 >/dev/null")
    else:
        ret = subprocess.call(cmd + args, env=os.environ)

    sys.exit(ret)

if __name__ == "__main__":
    main()
