#!/bin/zsh

# suspending...
###############
# error checking
if [[ $# -gt 0 ]] then  
  TIME=$(( $(date -d "$*" +%s) - $(date +%s)))
  if [[ $TIME -lt 0 || $TIME -gt $(( 24 * 60 * 60 )) ]] then
    echo "time $TIME seems invalid..."
    exit 1
  fi
  echo "going down for $(($TIME / 60)) minutes..."
else
  TIME=0
  echo "going down indefinitely..."
fi

# check if backup process is running
source $HOME/in/scripts/rbs
if [[ $(is_locked) == "locked" ]]; then
  echo -n "backup is in process right now, waiting a bit"
fi

while [[ $(is_locked) == "locked" ]]; do
  echo -n "."
  sleep 10
done

# sync drives in case of crash
sync

# daemons
/etc/init.d/fcron stop

# modules
if [[ $(hostname) == "nyarlathotep" || $(hostname) == "typhus" ]] then
  modprobe -r iwl3945 || exit 1
fi

# actual suspend
if [[ $TIME -gt 0 ]] then
  rtcwake -m mem -s $TIME
else
  s2ram -f
fi

# coming back...
################

if [[ $(hostname) == "nyarlathotep" || $(hostname) == "typhus" ]] then
  # wlan
  modprobe iwl3945 || exit 1
fi

# daemons
/etc/init.d/fcron start
