#!/usr/bin/env python3

import datetime, fileinput, re, sys

colors = {"none":'',
          "black":'\033[0;30m',
          "red":'\033[0;31m',
          "green":'\033[0;32m',
          "brown":"\033[0;33m",
          "blue":"\033[0;34m",\
          "purple":"\033[0;35m",
          "cyan":"\033[0;36m",
          "grey":"\033[0;37m",
          "light_black":"\033[1;30m",
          "light_red":"\033[1;31m",
          "light_green":"\033[1;32m",
          "light_brown":"\033[1;33m",
          "light_blue":"\033[1;34m",
          "light_purple":"\033[1;35m",
          "light_cyan":"\033[1;36m",
          "white":"\033[1;37m",
          "reset":"\033[0m", 
         }

today = datetime.date.today()
wdays = ["mon", "tue", "wed", "thu", "fri", "sat", "sun"]
date_re = re.compile("(\( (?P<year>\d+) / (?P<month>\d+) / (?P<day>\d+) \))",
                     re.X)

def parse_date(line, diff):
    date = today + datetime.timedelta(days=diff)
    new_date = "(%02d/%02d/%02d)" % (date.year - 2000, date.month, date.day)
    
    match = date_re.search(line)
    if match:
        line = date_re.sub(new_date, line)
    else:
        line = re.sub("\n\Z", " %s\n" % (new_date), line)

    return line

recur_re = re.compile("""
                      (^! | \s+!)
                      (?P<diff> \d+ )
                      (\s+ | $)
                      """, re.X)

def parse_recur(line):
    m = recur_re.search(line)
    if m:
        diff = int(m.group("diff"))
        return parse_date(line, diff)
    return line

def main():
    for line in fileinput.input():
        line = parse_recur(line)
        print(line, end="")

if __name__ == "__main__":
    main()

